
name: Create Branch For Branch

on:
  issues:
    types: [ assigned ]
  pull_request:
    branches: [ closed ]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest

    steps:
      - name: Create Branch For Issue
        id: Create_Branch_For_Issue
        uses: Algorithm/create-issue-branch@issue-handle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo branch name
        run: echo ${{ steps.Create_Branch_For_Issue.outputs.branchName }}

