name: issue branch Auto creation 

on:
  issues:
    types: [ assigned ]
  issue_comment:
    types: [created ]
  pull_request:
    types: [ closed ]

  workflow_dispatch:

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest

    steps:
      - name: Create Issue Branch
        uses: Algorithm/create_issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
